version: "3.7"

services:
  postgres-auth:
    image: postgres:latest
    container_name: postgres-auth
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: findit_auth
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - production-network

  redis-auth:
    image: redis:latest
    container_name: redis-auth
    command: redis-server --requirepass RedisFindit
    ports:
      - "6379:6379"
    networks:
      - production-network

  ms-auth:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: uemurabruno/findit-backend
    container_name: ms-auth
    depends_on:
      - postgres-auth
      - redis-auth
    restart: always
    networks:
      - production-network
    ports:
      - "4000:4000"

networks:
  production-network:
    driver: bridge
