version: "3.7"

services:
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: findit-rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - production-network

  auth-db:
    image: postgres:latest
    container_name: postgres-auth
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: findit_auth
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata_auth:/var/lib/postgresql/data
    networks:
      - production-network

  redis:
    image: redis:latest
    container_name: redis-auth
    command: redis-server --requirepass RedisFindit
    ports:
      - "6379:6379"
    networks:
      - production-network

  user-db:
    image: postgres:latest
    container_name: postgres-user
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: findit_user
    ports:
      - "15432:5432"
    volumes:
      - ./pgdata_user:/var/lib/postgresql/data
    networks:
      - production-network

  service-db:
    image: postgres:latest
    container_name: postgres-service
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: findit_service
    ports:
      - "25432:5432"
    volumes:
      - ./pgdata_service:/var/lib/postgresql/data
    networks:
      - production-network

  chat-db:
    image: postgres:latest
    container_name: postgres-chat
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: findit_chat
    ports:
      - "35432:5432"
    volumes:
      - ./pgdata_chat:/var/lib/postgresql/data
    networks:
      - production-network

networks:
  production-network:
    driver: bridge
