version: "3.7"

services:
  postgres-services:
    image: postgres:latest
    container_name: postgres-services
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: findit_service
    ports:
      - "25432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - production-network

  ms-services:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: ms-services
    depends_on:
      - postgres-services
    restart: always
    networks:
      - production-network
    ports:
      - "4002:4002"

networks:
  production-network:
    driver: bridge
