version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: ms-services-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: findit_service
    ports:
      - "25432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - production-network

  # app:
  #   build:
  #     dockerfile: ./Dockerfile
  #     context: .
  #   container_name: ms-services-node
  #   depends_on:
  #     - postgres
  #   restart: always
  #   networks:
  #     - production-network
  #   ports:
  #     - "4004:4004"

networks:
  production-network:
    driver: bridge
