GET http://localhost:4004/api/chats

#####################################################

GET http://localhost:4004/api/chatsById/cab8e028-ed9f-43a0-a18f-a4bf52bf125a

#####################################################

GET http://localhost:4004/api/chatsByUser/0862ba64-cc49-4e34-b82e-430a8415a8c4

#####################################################

GET http://localhost:4004/api/chat/messages/cab8e028-ed9f-43a0-a18f-a4bf52bf125a

#####################################################

POST http://localhost:4004/api/chat/create-chat
content-type: application/json

{
    "sender_id": "0862ba64-cc49-4e34-b82e-430a8415a8c4",
    "receiver_id": "55a3fa84-955b-42d7-85c7-6ad6b650d255"
}

#####################################################

POST http://localhost:4004/api/chat/send-message/cab8e028-ed9f-43a0-a18f-a4bf52bf125a
content-type: application/json

{
    "sender_id": "0862ba64-cc49-4e34-b82e-430a8415a8c4",
    "content": "Hello Sir, how are you?"
}
