version: "3.7"

services:
  postgres-users:
    image: postgres:latest
    container_name: postgres-users
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: findit_user
    ports:
      - "15432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - production-network

  ms-users:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: ms-users
    depends_on:
      - postgres-users
    restart: always
    networks:
      - production-network
    ports:
      - "4001:4001"
    volumes:
      - ./src/uploads:/usr/app/src/uploads

networks:
  production-network:
    driver: bridge
