version: "3.7"

services:
  userdb:
    image: postgres:latest
    container_name: ms-users-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: findit_user
    ports:
      - "15432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - production-network

  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: ms-users-node
    depends_on:
      - userdb
    restart: always
    networks:
      - production-network
    ports:
      - "4001:4001"
    volumes:
      - ./src/uploads:/usr/app/src/uploads

  # nginx:
  #   build:
  #     dockerfile: ./docker/nginx.dockerfile
  #     context: .
  #   image: uemurabruno/nginx
  #   container_name: nginx
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - production-network
  #   depends_on:
  #     - node1
  #     - node2
  #     - node3

networks:
  production-network:
    driver: bridge
