version: "3.7"

services:
  userdb:
    image: postgres:latest
    container_name: ms-users-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: findit_user
    ports:
      - "15432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - production-network

  # app:
  #   build:
  #     dockerfile: ./Dockerfile
  #     context: .
  #   container_name: ms-users-node
  #   depends_on:
  #     - userdb
  #   restart: always
  #   networks:
  #     - production-network
  #   ports:
  #     - "4001:4001"
  #   volumes:
  #     - ./src/uploads:/usr/app/src/uploads

networks:
  production-network:
    driver: bridge
