POST http://localhost:4000/api/auth/register
content-type: application/json

{
	"name": "Bruno Uemura",	
	"email": "bruno.uemura1@gmail.com",
	"password": "test"
}

###

GET http://localhost:4000/api/auth/email-confirmation/:id

###

POST http://localhost:4000/api/auth/login
content-type: application/json

{
	"email": "bruno.uemura@gmail.com",
	"password": "test"	
}

###

POST http://localhost:4000/api/auth/logout
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJlMzllOWQ5LTgzMTgtNDRiNS1hNWU0LTA2YzE3NDFjYjZkNiIsImVtYWlsIjoibGludXMudG9ydmFsZHNAZ21haWwuY29tIiwiaWF0IjoxNjMxMjQ3NzgwLCJleHAiOjE2MzEyNTEzODB9.dKKyHrejNvJFUK5y9nipYYq351vHzc2iNWA6P8sC6Ps"
}