GET http://localhost:4001/api/users


###

GET http://localhost:4001/api/users/3cfe35ca-7156-4513-af6a-cc846179c8be

###

PUT http://localhost:4001/api/users/66ee85c5-75f4-4516-b20f-9a12d2549445
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJlMzllOWQ5LTgzMTgtNDRiNS1hNWU0LTA2YzE3NDFjYjZkNiIsImVtYWlsIjoibGludXMudG9ydmFsZHNAZ21haWwuY29tIiwiaWF0IjoxNjMxMjQ2MTIwLCJleHAiOjE2MzEyNDk3MjB9.HkJqMOHIUPnxoLE_IWeLRehDKty0dmCpi9IqTXakUrg

{
	"name": "Bruno Uemura",
	"user_photo": null,
	"city": "Campinas",
	"state": "São Paulo",
	"country": "Brazil",
	"phone": "+55 19 99999-9999",
	"occupation": "Software Engineer",
	"about_me": "I am a Software Engineer"
}

###

DELETE http://localhost:4001/api/users/66ee85c5-75f4-4516-b20f-9a12d2549445
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJlMzllOWQ5LTgzMTgtNDRiNS1hNWU0LTA2YzE3NDFjYjZkNiIsImVtYWlsIjoibGludXMudG9ydmFsZHNAZ21haWwuY29tIiwiaWF0IjoxNjMxMjQ2MTIwLCJleHAiOjE2MzEyNDk3MjB9.HkJqMOHIUPnxoLE_IWeLRehDKty0dmCpi9IqTXakUrg
